## Add/Remove Rows and Columns From DataFrames

In [15]:
import pandas as pd
import numpy as np

以下為 Python dictionary 各種寫法

In [16]:
person = {"first": "Corey",
          "last": "Schafer",
          "email": "CoreySchafer@gmail.com"}

In [17]:
people = {"first": ["Corey"],
          "last": ["Schafer"],
          "email": ["CoreySchafer@gmail.com"]}

In [18]:
people = {"first": ["Corey", "Jane", "John"],
          "last": ["Schafer", "Doe", "Doe"],
          "email": ["CoreySchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"]}

In [19]:
df = pd.DataFrame(people) # pandas 可以直接讀取 dictionary 格式

In [20]:
df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [14]:
df.sort_values(by=['last']) # sort_values 針對列索引資料排序(default ascending=True) 優先第一個英文字母順序 次優先字串長度 若都相同則會比第二個英文字母順序... 以此類推 若為數字則由小到大 (此結果未存回原資料)

   first     last                   email
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
0  Corey  Schafer  CoreySchafer@gmail.com

In [21]:
df.sort_values(by=['last', 'first']) # 當複數個列索引同時排列 先排好的不會被後面排的影響 也就是說後面的 'first' 想改變 'last' 的順序已經不可能 (此結果未存回原資料)

   first     last                   email
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
0  Corey  Schafer  CoreySchafer@gmail.com

In [22]:
df.sort_values(by=['last'], ascending=False) # ascending 升冪排序(pandas 中的升冪為向下 若為 False 則向上) 若為 False 則排序後面的元素會在前面 (此結果未存回原資料)

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [10]:
df.sort_values(by=['last', 'first'], ascending=False) # 因為在 'last' 中排序優先度相同都是 'Doe' 但是在 'first' 中 Jane 的排序優先度應該大於 John 又因為 ascending=False 所以要把正常來說應該排在後面的元素排在前面 (此結果未存回原資料)

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
2   John      Doe       JohnDoe@gmail.com
1   Jane      Doe       JaneDoe@gmail.com

In [23]:
people = {"first": ["Corey", "Jane", "John", "Adam"],
          "last": ["Schafer", "Doe", "Doe", "Doe"],
          "email": ["CoreySchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com", "A@gmail.com"]}

In [24]:
df2 = pd.DataFrame(people)

In [25]:
df2

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
3   Adam      Doe             A@gmail.com

In [26]:
df2.sort_values(by=['last']) # (此結果未存回原資料)

   first     last                   email
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
3   Adam      Doe             A@gmail.com
0  Corey  Schafer  CoreySchafer@gmail.com

In [27]:
df2.sort_values(by=['last', 'first']) # (此結果未存回原資料)

   first     last                   email
3   Adam      Doe             A@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
0  Corey  Schafer  CoreySchafer@gmail.com

In [16]:
df2.sort_values(by=['last'], ascending=False) # (此結果未存回原資料)

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
3   Adam      Doe             A@gmail.com

In [17]:
df2.sort_values(by=['last', 'first'], ascending=[False, True], inplace=True) # 與前面用法相似但是這邊分別指定不同列索引的 ascending 布靈值 且寫入原資料中使改變生效

In [18]:
df2.sort_index() # 排列行索引 直接將被改變排序的資料轉換回原始資料 (注意:這邊會直接再寫入資料並儲存)

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com
3   Adam      Doe             A@gmail.com

In [19]:
df2 # 如上述

   first     last                   email
0  Corey  Schafer  CoreySchafer@gmail.com
3   Adam      Doe             A@gmail.com
1   Jane      Doe       JaneDoe@gmail.com
2   John      Doe       JohnDoe@gmail.com

In [20]:
df2['last'].sort_values() # 另一種指定列索引處理排序的方式 (此結果未存回原資料)

3        Doe
1        Doe
2        Doe
0    Schafer
Name: last, dtype: object

In [21]:
public_df = pd.read_csv('../pandas_dataset/developer_survey_2020/survey_results_public.csv')
schema_df = pd.read_csv('../pandas_dataset/developer_survey_2020/survey_results_schema.csv')

In [22]:
pd.set_option('display.max_columns', 100) #設定顯示 column 數量
pd.set_option('display.max_rows', 100) #設定顯示 row 數量

In [23]:
public_df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [24]:
public_df.sort_values(by=['Country', 'ConvertedComp'], ascending=[True, False], inplace=True)

In [25]:
public_df[['Country', 'ConvertedComp']].head(100) # 這裡比較值得注意的是 NaN 會排在非 NaN 的資料後面

           Country  ConvertedComp
61540  Afghanistan      1000000.0
63925  Afghanistan      1000000.0
63993  Afghanistan      1000000.0
38261  Afghanistan       231192.0
28270  Afghanistan       130000.0
9806   Afghanistan        23328.0
62520  Afghanistan        23328.0
50812  Afghanistan        20950.0
50469  Afghanistan        20220.0
43642  Afghanistan        18660.0
15371  Afghanistan        18000.0
2918   Afghanistan        16335.0
26443  Afghanistan        13992.0
56146  Afghanistan        10884.0
26676  Afghanistan         8016.0
30451  Afghanistan         5448.0
30405  Afghanistan         4668.0
28704  Afghanistan         4509.0
34842  Afghanistan         4356.0
26758  Afghanistan         2328.0
33755  Afghanistan         1860.0
35602  Afghanistan          780.0
17985  Afghanistan          109.0
35168  Afghanistan            0.0
895    Afghanistan            NaN
5948   Afghanistan            NaN
7586   Afghanistan            NaN
7678   Afghanistan            NaN
8599   Afghanistan            NaN
8824   Afghanistan            NaN
9454   Afghanistan            NaN
9585   Afghanistan            NaN
10317  Afghanistan            NaN
23708  Afghanistan            NaN
24124  Afghanistan            NaN
24908  Afghanistan            NaN
26477  Afghanistan            NaN
26496  Afghanistan            NaN
26525  Afghanistan            NaN
29781  Afghanistan            NaN
30491  Afghanistan            NaN
31199  Afghanistan            NaN
35052  Afghanistan            NaN
35511  Afghanistan            NaN
35541  Afghanistan            NaN
36354  Afghanistan            NaN
36887  Afghanistan            NaN
37284  Afghanistan            NaN
37371  Afghanistan            NaN
37601  Afghanistan            NaN
38761  Afghanistan            NaN
39097  Afghanistan            NaN
39808  Afghanistan            NaN
41506  Afghanistan            NaN
41950  Afghanistan            NaN
42432  Afghanistan            NaN
43010  Afghanistan            NaN
43140  Afghanistan            NaN
43157  Afghanistan            NaN
43708  Afghanistan            NaN
43709  Afghanistan            NaN
43843  Afghanistan            NaN
44504  Afghanistan            NaN
44571  Afghanistan            NaN
45037  Afghanistan            NaN
45879  Afghanistan            NaN
50492  Afghanistan            NaN
50641  Afghanistan            NaN
50847  Afghanistan            NaN
51804  Afghanistan            NaN
53923  Afghanistan            NaN
54129  Afghanistan            NaN
56507  Afghanistan            NaN
57044  Afghanistan            NaN
59329  Afghanistan            NaN
61453  Afghanistan            NaN
61694  Afghanistan            NaN
62196  Afghanistan            NaN
62210  Afghanistan            NaN
62227  Afghanistan            NaN
64197  Afghanistan            NaN
64297  Afghanistan            NaN
64306  Afghanistan            NaN
64343  Afghanistan            NaN
23253      Albania       194580.0
19588      Albania        32652.0
13025      Albania        31788.0
44194      Albania        31788.0
10613      Albania        25944.0
26744      Albania        25944.0
17168      Albania        23316.0
57300      Albania        21192.0
59859      Albania        16860.0
21867      Albania        15900.0
28793      Albania        15900.0
50480      Albania        15900.0
23409      Albania        13776.0
37216      Albania        12972.0
562        Albania        10812.0
27611      Albania        10596.0

In [26]:
public_df['ConvertedComp'].nlargest(10) # 找出 'ConvertedComp' 中最大的前十個值 (此結果未存回原資料)

5701     2000000.0
53175    2000000.0
42657    2000000.0
58136    2000000.0
45753    2000000.0
121      2000000.0
123      2000000.0
191      2000000.0
663      2000000.0
697      2000000.0
Name: ConvertedComp, dtype: float64

In [29]:
public_df.loc[public_df['ConvertedComp'].nlargest(10).index, 'Country'] # 利用找出上面結果的 index 輸出列索引 'Country' 的元素

5701            Canada
53175           Canada
42657            Italy
58136            Nepal
45753          Nomadic
121      United States
123      United States
191      United States
663      United States
697      United States
Name: Country, dtype: object

In [57]:
public_df['ConvertedComp'].nlargest(10).index # 找出 'ConvertedComp' 中最大的前十個值的行索引 (此結果未存回原資料)

Int64Index([53175, 5701, 42657, 58136, 45753, 1784, 3058, 3031, 1407, 3247], dtype='int64')

In [58]:
public_df.nlargest(10, 'ConvertedComp') # 類似的操作但是結果不同 這邊變成搜尋條件是 'ConvertedComp' 最大的前十筆 搜尋範圍是整個資料以 'ConvertedComp' 來排序(此結果未存回原資料)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
53175,54263,I am a developer by profession,Yes,29.0,10,Weekly,7.000000e+04,2000000.0,Canada,United States dollar,USD,Redis,Firebase;PostgreSQL;SQLite,"Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,South Asian,Man,"Flex time or a flexible schedule;Languages, fr...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Go;Haskell;Rust,Dart;Java;JavaScript;Kotlin;Python;TypeScript,React Native;TensorFlow;Torch/PyTorch,Flutter;Node.js,Facebook Workplace,Confluence;Jira;Github;Gitlab;Slack;Microsoft ...,Yes,Extremely important,Somewhat important,Just because;Curious about other opportunities...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Yes,Yes,Rarely: 1-2 days per year or less,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Go for a walk or...,MacOS,NaN,Docker;Heroku;iOS;Kubernetes,Android;AWS;Linux,I have some influence,Straight / Heterosexual,Not sure/can't remember,"Yes, somewhat",NaN,Daily or almost daily,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js;Vue.js,Express;Flask;jQuery,Just as welcome now as I felt last year,36.0,14,5
5701,5725,I am a developer by profession,No,26.0,14,Monthly,1.800000e+05,2000000.0,Canada,United States dollar,USD,Redis,NaN,"Developer, back-end;DevOps specialist","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,Go;Python;Ruby;TypeScript,Bash/Shell/PowerShell;JavaScript;Python,Teraform,NaN,"Github;Gitlab;Google Suite (Docs, Meet, etc)","Github;Google Suite (Docs, Meet, etc)",Yes,Extremely important,Very important,Trouble with my teammates;Better work/life bal...,"Read company media, such as employee blogs or ...",Once a year,No,Yes,No,Often: 1-2 days per week or more,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Go for a walk or oth...,Linux-based,"10,000 or more employees",Docker;Google Cloud Platform,Docker;Google Cloud Platform,I have little or no influence,Straight / Heterosexual,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Gatsby,Spring,Not applicable - I did not use Stack Overflow ...,40.0,10,4
42657,43430,I am a developer by profession,Yes,33.0,17,Monthly,1.710000e+05,2000000.0,Italy,United States dollar,USD,NaN,NaN,"Academic researcher;Developer, back-end;Develo...","Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Assembly;Bash/Shell/PowerShell;C;C++;Perl;Python,Assembly;Bash/Shell/PowerShell;C;C++;Perl;Python,NaN,NaN,Confluence;Jira;Github;Gitlab;Slack;Google Sui...,Confluence;Jira;Github;Gitlab;Slack;Google Sui...,Yes,Somewhat important,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once every few years,Not sure,Yes,No,Often: 1-2 days per week or more,Start a free trial,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Go for a walk or oth...,Linux-based,"10,000 or more employees",Android;Linux;MacOS;Windows,Android;Linux;MacOS;Windows,I have some influence,Straight / Heterosexual,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,13,2
58136,59279,I am a developer by profession,Yes,NaN,12,Monthly,3.000000e+05,2000000.0,Nepal,United States dollar,USD,Cassandra;Couchbase;DynamoDB;IBM DB2;MariaDB;M...,Elasticsearch;Firebase;Microsoft SQL Server;My...,Data or business analyst;Data scientist or mac...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,South Asian;Southeast Asian,NaN,Flex time or a flexible schedule;Remote work o...,Very satisfied,"I’m not actively looking, but I am open to new...",Dart;Go;Haskell;Julia;Kotlin;Perl;PHP;R;Ruby;R...,Assembly;Bash/Shell/PowerShell;C;C#;C++;HTML/C...,Ansible;Apache Spark;Flutter;Hadoop;Keras;Pand...,.NET;.NET Core;Chef;Cordova;Node.js;React Nati...,Gitlab;Trello,Confluence;Jira;Github;Facebook Workplace;Slac...,Yes,Extremely important,NaN,Having a bad day (or week or month) at work;Tr...,"Read company media, such as employee blogs or ...",NaN,Yes,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,"1,000 to 4,999 employees",Arduino;Heroku;IBM Cloud or Watson;Kubernetes;...,Android;AWS;Docker;Google Cloud Platform;iOS;L...,I have a great deal of influence,NaN,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Multiple times per day,Neither easy nor difficult,Too long,NaN,"Computer science, computer engineering, or sof...",Django;Drupal;Flask;Gatsby;Laravel,Angular;Angular.js;ASP.NET;ASP.NET Core;Expres...,A lot more welcome now than last year,40.0,20,14
45753,46711,I am a developer by profession,Yes,NaN,Younger than 5 years,Yearly,1.000000e+56,2000000.0,Nomadic,United States dollar,USD,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Academic researcher;Data or business analyst;D...,Primary/elementary school,Employed full-time,NaN,NaN,"Languages, frameworks, and other technologies ...",Very satisfied,"I’m not actively looking, but I am open to new...",Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,.NET;.NET Core;Ansible;Apache Spark;Chef;Cordo...,.NET;.NET Core;Ansible;Apache Spark;Chef;Cordo...,Confluence;Jira;Github;Gitlab;Facebook Workpla...,Confluence;Jira;Github;Gitlab;Facebook Workpla...,Yes,Extremely important,Not at all important/not necessary,Just because;Having a bad day (or week or mont...,"Read company media, such as employee blogs or ...",Every few months,NaN,Yes,NaN,Often: 1-2 days per week or more,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Play games;Call a coworker or friend;...,NaN,"10,000 or more employees",Android;Arduino;AWS;Docker;Google Cloud Platfo...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,I have little or no influence,NaN,NaN,NaN,NaN,Multiple times per day,NaN,NaN,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,NaN,168.0,More than 50 years,More than 50 years
1784,1793,I am a developer by profession,Yes,27.0,16,Weekly,1.200000e+05,2000000.0,United States,United States dollar,USD,MariaDB;PostgreSQL;Redis,Elasticsearch;Oracle;SQLite,"Developer, back-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Dart;Go;Ruby,Bash/Shell/PowerShell;C++;HTML/CSS;Python;Rust...,NaN,Ansible,NaN,Confluence;Jira;Github;Microsoft Teams,Yes,Neutral,Very important,Just because;Having a bad day (or week or mont...,"Read company media, such as employee blogs or ...",Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Linux-based,"1,000 to 4,999 employees",Android;Arduino,Docker;Linux;Raspberry Pi,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,12,NaN
3058,3072,I am a developer by profession,Yes,32.0,22,Weekly,1.020000e+05,2000000.0,United States,United States dollar,USD,MongoDB,Microsoft SQL Server;Redis,Data scientist or machine learning specialist;...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",C#;Python;Rust,C#;Python,.NET Core;Cordova;Pandas;TensorFlow;Torch/PyTorch,.NET Core;Pandas,Confluence;Gitlab;Microsoft Teams;Microsoft Az...,Confluence;Gitlab;Microsoft Azure,Yes,Extremely important,Very important,Curious about other opportunities;Growth or le...,"Read company media, such as employee blogs or ...",Once a year,No,No,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Play games;Call a coworker or friend;...,Windows,"10,000 or more employees",Docker;Linux;Windows,Docker;Linux;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Flask,ASP.NET Core,Somewhat less welcome now than last year,40.0,10,7
3031,3045,I am a developer by profession,Yes,35.0,12,Weekly,1.000000e+05,2000000.0,United States,United States dollar,USD,MongoDB;MySQL;Oracle;PostgreSQL;SQLite,DynamoDB;MariaDB;Microsoft SQL Server;MongoDB;...,"Developer, back-end;Developer, desktop or ente...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Office environment or company culture;Opportun...,Slightly dissatisfied,I am actively looking for a job,Bash/Shell/PowerShell;C#;C++;Go;HTML/CSS;Java;...,Bash/Shell/PowerShell;C;C#;C++;Go;HTML/CSS;Jav...,.NET;.NET Core;Apache Spark;Hadoop;Unity 3D;Un...,.NET;.NET Core;Apache Spark;Hadoop;Node.js;Uni...,Github;Microsoft Teams;Microsoft Azure;Google ...,Github;Slack;Microsoft Teams;Microsoft Azure;G...,No,Not very important,Very important,Having a bad day (or week or month) at work;Wa...,Company reviews from third party sites (e.g. G...,Every few months,No,No,No,Sometimes: 1-2 days per month but less than we...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Go for a walk ...,Windows,100 to 499 employees,Android;AWS;iOS;Kubernetes;Linux;MacOS;Microso...,Android;AWS;Linux;MacOS;Microsoft Azure;Windows,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,42.0,23,5
1407,1413,I am a developer by profession,Yes,25.0,12,Weekly,4.100000e+04,2000000.0,United States,United States dollar,USD,Microsoft SQL Server;MySQL,Microsoft SQL Server;MySQL,"Database administrator;Designer;Developer, bac...",Some college/university study without earning ...,Employed full-time,White or of European descent,"Non-binary, genderqueer, or gender non-conforming",Flex time or a flexible schedule;How widely us...,Slightly satisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...,NaN,NaN,Jira;Github,Github,No,Neutral,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",NaN,Yes,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Windows,500 to 999 employees,Linux;Raspberry Pi;Windows,Linux;Raspberry Pi;Windows;WordPress,I have some influence,Bisexual,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel,jQuery,Just as welcome now as I felt last year,37.0,13,3
3247,3261,I am a developer by profession,Yes,34.0,23,Weekly,1.150000e+05,2000000.0,United States,United States dollar,USD,DynamoDB;MySQL;Redis,DynamoDB;MongoDB,Data scientist or machine learning specialist;...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",White or of European descent;South Asian;Multi...,Man,"Languages, frameworks, and other technologies ...",Very dissatisfied,I am actively looking for a job,HTML/CSS;Java;JavaScript;Python,HTML/CSS;Java;JavaScript;Python,NaN,NaN,Confluence;Jira;Github;Slack;Google Suite (Doc...,Confluence;Jira;Github;Slack;Google Suite (Doc...,Yes,Extremely important,Critically important,Having a bad day (or week or month) at work;Cu...,"Read company media, such as employee blogs or ...",Once every few years,No,No,No,Often: 1-2 days per week or more,Visit developer communities like Stack Overflow,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,MacOS,100 to 499 employees,AWS;Kubernetes,AWS,NaN,Straight / Heterosexual,Yes,"Yes, definitely",I have never participated in Q&A on Stack Over...,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;jQuery;Spring,Spring,Just as welcome now as I felt last year,60.0,11,9

In [59]:
public_df.nsmallest(10, 'ConvertedComp') # 這裡值得注意的是 找最小值並不會回傳 NaN (找最大值也不會)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
35168,35295,I am a developer by profession,Yes,NaN,13,Monthly,2.0,0.0,Afghanistan,Afghan afghani,AFN,NaN,MySQL;PostgreSQL;SQLite,Academic researcher;Educator;Scientist,"Other doctoral degree (Ph.D., Ed.D., etc.)","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,Very dissatisfied,I am actively looking for a job,NaN,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,NaN,TensorFlow;Unity 3D,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a year,Yes,Onboarding? What onboarding?,Yes,Often: 1-2 days per week or more,Read ratings or reviews on third party sites l...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Go for a walk or other physical act...,Linux-based,"Just me - I am a freelancer, sole proprietor, ...",NaN,Android;iOS;Linux;MacOS,NaN,NaN,Yes,"No, not at all",Less than once per month or monthly,Multiple times per day,Neither easy nor difficult,Appropriate in length,NaN,"Another engineering discipline (such as civil,...",NaN,jQuery,A lot less welcome now than last year,100.0,35,27
46385,47357,I am a developer by profession,Yes,NaN,5,Weekly,1.0,0.0,Albania,Bhutanese ngultrum,BTN,MariaDB,NaN,Academic researcher,Primary/elementary school,Employed full-time,NaN,NaN,Family friendliness,Neither satisfied nor dissatisfied,I am actively looking for a job,Bash/Shell/PowerShell;C,NaN,Hadoop,NaN,"Google Suite (Docs, Meet, etc)",NaN,No,Extremely important,Somewhat important,Just because,"Read company media, such as employee blogs or ...",Once a decade,NaN,Yes,No,Rarely: 1-2 days per year or less,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Play games,Linux-based,"Just me - I am a freelancer, sole proprietor, ...",AWS,NaN,NaN,NaN,Yes,"No, not at all",Daily or almost daily,A few times per month or weekly,NaN,NaN,NaN,NaN,Drupal,NaN,Somewhat less welcome now than last year,168.0,2,11
27035,27135,I am a developer by profession,No,NaN,16,Yearly,0.0,0.0,Australia,Australian dollar,AUD,MySQL,MySQL,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",NaN,Man,Industry that I’d be working in;How widely use...,Very satisfied,"I’m not actively looking, but I am open to new...",Go;HTML/CSS;JavaScript;Python;SQL,HTML/CSS;JavaScript;PHP;Python;R;SQL;VBA,Apache Spark;Node.js;Pandas;TensorFlow;Torch/P...,Apache Spark;Node.js;Pandas;TensorFlow;Torch/P...,Jira;Github;Trello,Jira;Github;Trello,No,Extremely important,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Start a free trial;Visit developer communities...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Go for a walk ...,Windows,2 to 9 employees,Raspberry Pi;Windows,Google Cloud Platform;Raspberry Pi;Windows,NaN,NaN,Yes,"No, not really",I have never participated in Q&A on Stack Over...,A few times per week,Neither easy nor difficult,Appropriate in length,No,"A humanities discipline (such as literature, h...",Angular.js;Django;jQuery;React.js;Vue.js,Django;jQuery;React.js,Just as welcome now as I felt last year,80.0,15,15
6029,6054,I am a developer by profession,Yes,38.0,15,Yearly,0.0,0.0,Australia,Australian dollar,AUD,NaN,MySQL,"Designer;Developer, back-end;Developer, front-...","Secondary school (e.g. American high school, G...","Independent contractor, freelancer, or self-em...",NaN,Man,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,I am not interested in new job opportunities,NaN,PHP,NaN,NaN,NaN,NaN,No,Neutral,Not at all important/not necessary,NaN,NaN,Once every few years,Not sure,Onboarding? What onboarding?,Yes,Often: 1-2 days per week or more,NaN,Indifferent,Stack Overflow (public Q&A for anyone who code...,NaN,MacOS,"Just me - I am a freelancer, sole proprietor, ...",NaN,MacOS,NaN,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,Easy,Too long,No,NaN,NaN,Laravel,A lot less welcome now than last year,30.0,22,20
59118,60292,I am a developer by profession,Yes,NaN,12,Yearly,0.0,0.0,Austria,European Euro,EUR,NaN,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,000 or more employees",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,18,10
38395,38813,I am a developer by profession,No,NaN,18,Monthly,0.0,0.0,Azerbaijan,Azerbaijan manat,AZN,NaN,NaN,Academic researcher;Data or business analyst;D...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Critically important,NaN,NaN,NaN,Not sure,NaN,Yes,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,2 to 9 employees,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,4,3
8438,8470,I am a developer by profession,Yes,NaN,5,Monthly,30.0,0.0,Bangladesh,Bangladeshi taka,BDT,Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQ...,Firebase;MongoDB;MySQL;Oracle;PostgreSQL;Redis,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,NaN,NaN,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;Dart;Go;JavaScript;Pytho...,Assembly;Bash/Shell/PowerShell;C;HTML/CSS;Java...,Flutter;Node.js;React Native;TensorFlow,Node.js,Jira;Github;Gitlab;Slack;Trello;Google Suite (...,Jira;Github;Gitlab;Slack;Trello;Google Suite (...,No,Extremely important,NaN,Curious about other opportunities;Better compe...,NaN,Every few months,NaN,NaN,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,MacOS,20 to 99 employees,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Docker;Heroku;Linux;MacOS,NaN,NaN,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;Laravel;React.js;Vue.js,Django;Express;Gatsby;Laravel;React.js;Vue.js,NaN,NaN,4,2
40410,41006,I am a developer by profession,Yes,22.0,17,Yearly,0.0,0.0,Belgium,Pound sterling,GBP,NaN,Firebase;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",Middle Eastern,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",C++;Go;Kotlin;Python;Rust,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,React Native;TensorFlow,.NET Core;Node.js,NaN,"Github;Gitlab;Trello;Google Suite (Docs, Meet,...",No,Extremely important,Not at all important/not necessary,NaN,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Read ratings or reviews on third party sites l...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Panic;Do other work and c...,Linux-based,"Just me - I am a freelancer, sole proprietor, ...",Android;iOS;MacOS;Windows,Docker;Google Cloud Platform;Kubernetes;Linux,NaN,Bisexual,Yes,Neutral,A few times per month or weekly,Daily or almost daily,Easy,Appropriate in length,No,"A business discipline (such as accounting, fin...",NaN,Angular;ASP.NET Core;React.js;Spring,Just as welcome now as I felt last year,30.0,4,3
15442,15493,I am a developer by profession,No,44.0,17,Monthly,0.0,0.0,Brazil,Brazilian real,BRL,DynamoDB,DynamoDB,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",JavaScript,HTML/CSS;JavaScript,Node.js;React Native;Teraform,Node.js,Github;Facebook Workplace,Github;Slack;Trello,No,Extremely important,Somewhat important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Once a decade,No,No,Yes,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,"Just me - I am a freelancer, sole proprietor, ...",AWS;Google Cloud Platform,AWS,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"A business discipline (such as accounting, fin...",React.js,React.js,Just as welcome now as I felt last year,60.0,10,4
56246,57369,I am a developer by profession,No,44.0,18,Monthly,0.0,0.0,Brazil,Brazilian real,BRL,DynamoDB,DynamoDB;MongoDB,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Middle Eastern,Man,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",JavaScript,JavaScript,Node.js;React Native;Teraform,Node.js,Github;Gitlab;Facebook Workplace;Trello;Stack ...,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",No,Somewhat important,Somewhat important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a decade,No,No,Yes,Often: 1-2 days per week or more,Start a free trial;Visit developer communities...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,"Just me - I am a freelancer, sole proprietor, ...",AWS,AWS,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Multiple times per day,Easy,Too long,No,"A business discipline (such as accounting, fin...",React.js,React.js,Just as welcome now as I felt last year,60.0,10,5